%low pass filters
clc;
clear all;
close all;
wc=0.5*pi;
N=input('Enter the value of N:');
alpha=(N-1)/2;
eps=0.001;
hd=sin(wc*(N-alpha+eps))./(pi*(N-alpha+eps));
wr=boxcar(N);
hn=hd.*wr;
w=0:0.1:pi;
h=freqz(hn,1,w);
subplot(2,1,1);
plot(w/pi,10*log10(abs(h)));
title('low pass filter using rectangular window');
xlabel('normalized frequency');
ylabel('magnitude in db');
subplot(2,1,2);
stem(wr);
title('rectangular window');
xlabel('no of samples');
ylabel('amplitude');
%high pass filter
clear all;
close all;
wc=0.5*pi;
N=input('Enter the value of N:');
alpha=(N-1)/2;
eps=0.001;
hd=sin(pi*(N-alpha+eps))-sin(wc*(N-alpha+eps))./(pi*(N-alpha+eps));
wr=boxcar(N);
hn=hd.*wr;
w=0:0.1:pi;
h=freqz(hn,1,w);
subplot(2,1,1);
plot(w/pi,10*log10(abs(h)));
title('high pass filter using rectangular window');
xlabel('normalized frequency');
ylabel('magnitude in db');
subplot(2,1,2);
stem(wr);
title('rectangular window');
xlabel('no of samples');
ylabel('amplitude');
%band pass filter
clear all;
close all;
wc1=0.25*pi;
wc2=0.75*pi;
N=input('Enter the value of N:');
alpha=(N-1)/2;
eps=0.001;
n=0:1:N-1;
hd=sin(wc2*(n-alpha+eps))-sin(wc1*(n-alpha+eps))./(pi*(n-alpha+eps));
wr=boxcar(N);
hn=hd.*wr';
w=0:0.1:pi;
h=freqz(hn,1,w);
subplot(2,1,1);
plot(w/pi,10*log10(abs(h)));
title('band pass filter using rectangular window');
xlabel('normalized frequency');
ylabel('magnitude in db');
subplot(2,1,2);
stem(wr);
title('rectangular window');
xlabel('no of samples');
ylabel('amplitude');

